# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nodeapp-deployment
#   labels:
#     app: hello-node
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: hello-node
#   template:
#     metadata:
#       labels:
#         app: hello-node 
#     spec:
#       containers:
#       - name: nodeserver
#         image: kabanchikua/testtatsk:latest
#         ports:
#         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      port: 3000
      targetPort: 3000
  selector:
    app: nodeapp
---

apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodepod
    image: kabanchikua/testtatsk:latest
    ports:
    - containerPort: 3000