apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: kabanchikua/testtatsk:latest
        ports:
        - containerPort: 4000
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: nodeapp-deployment
#   labels:
#     app: nodeapp
# spec:
#   ports:
#     - port: 3000
#       name: http
#   selector:
#     app: nodeapp

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: nodeapp
spec:
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
  selector:
    app: nodeapp
