
apiVersion: v1
kind: Pod
metadata:
  name: docker-push-pod
spec:
  containers:
    - name: docker
      image: docker
      command:
        - sh
        - -c
        - |
          apk update && apk add --no-cache git
          git clone https://github.com/SerhiiHnstl/Deploytestapp.git /Deploytestapp
          echo "Cloning completed"
          cd Deploytestapp/Nodejs
          echo "Navigated to /app/Nodejs"
          docker login --username=kabanchikua --password=dckr_pat_hMxvglq9AHtHplkJR3Wxf-J5mdI
          echo "Docker login completed"
          docker build -t kabanchikua/testtask:latest .
          echo "Docker build completed"
          docker push kabanchikua/testtask:latest
          echo "Docker push completed"



